#use std_core::io::IO;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;

#struct(rc) Point : Type[0] {
    x : i32,
    y : i32,
}

#proc set_point_ref : (point_ref : &^ Point) -> (code_ref : &^ i32) -> () {
    point_ref .> set Point { x = 20i32, y = 22i32 };
    code_ref .> set (i32_add point_ref.x point_ref.y);
    ()
}

#entrypoint main;

#fn main : () #with IO {
    #let point : Point = Point { x = 1i32, y = 2i32 };
    #letref #excl point_ref : &^ Point #borrow point;
    #let code_ref : i32 = 0i32;
    #letref #excl code_ref : &^ i32 #borrow code_ref;
    set_point_ref point_ref code_ref;
    #let _ : () <- IO::exit (code_ref .> get);
    ()
}
