#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_set;
#use std_core::io::IO;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;

#struct Span : Type[0] {
    start : i32,
    end : i32,
}

#fn set_span_ref : (span_ref : &^ Span) -> (code_ref : &^ i32) -> () #with IO {
    ref_set Span span_ref Span { start = 20i32, end = 22i32 };
    ref_set i32 code_ref (i32_add span_ref.start span_ref.end);
    ()
}

#entrypoint main;

#fn main : () #with IO {
    #let span : Span = Span { start = 1i32, end = 2i32 };
    #letref #excl span_ref : &^ Span #borrow span;
    #let code_ref : i32 = 0i32;
    #letref #excl code_ref : &^ i32 #borrow code_ref;
    set_span_ref span_ref code_ref;
    #let code : i32 = ref_get i32 code_ref;
    #let _ : () <- IO::exit code;
    ()
}
