#use std_core::io::IO;
#use std_core::primitive::array::Array;
#use std_core::primitive::array::array_get;
#use std_core::primitive::array::array_set;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;

#entrypoint main;

#fn sum3 : (array_ref : &^ Array i32 4i32) -> i32 #with IO {
    #let a0 : i32 = array_get array_ref 0i32;
    #let a1 : i32 = array_get array_ref 1i32;
    #let a2 : i32 = array_get array_ref 2i32;
    #let a0_plus_a1 : i32 = i32_add a0 a1;
    i32_add a0_plus_a1 a2
}

#fn main : () #with IO {
    #let array_ref : Array i32 4i32 <- IO::array_new i32 4i32;
    #letref #excl array_write_ref : &^ Array i32 4i32 #borrow array_ref;
    array_set array_write_ref 0i32 7i32;
    array_set array_write_ref 1i32 14i32;
    array_set array_write_ref 2i32 21i32;
    #let r : i32 <- sum3 array_write_ref;
    #let _ : () <- IO::exit r;
    ()
}
