#use std_core::io::IO;
#use std_core::ptx::PTX;
#use std_core::primitive::array::ArrayVL;
#use std_core::primitive::array::ArrayVLPTX;
#use std_core::primitive::bool::bool_and;
#use std_core::primitive::f32::f32;
#use std_core::primitive::f32::f32_add;
#use std_core::primitive::f32::f32_div;
#use std_core::primitive::f32::f32_mul;
#use std_core::primitive::f32::f32_sqrt;
#use std_core::primitive::f32::f32_sub;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_eq;
#use std_core::primitive::i64::i64;
#use std_core::primitive::i64::i64_add;
#use std_core::primitive::i64::i64_div;
#use std_core::primitive::i64::i64_mul;
#use std_core::primitive::i64::i64_sub;
#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_get_ptx;
#use std_core::primitive::reference::ref_set_ptx;
#use std_core::primitive::u8::u8;

#fn i64_kernel : (array : ArrayVLPTX i64) -> () #with PTX {
    #let a : i64 = ref_get_ptx i64 array 0i32;
    #let b : i64 = ref_get_ptx i64 array 1i32;
    #let sum : i64 = i64_add a b;
    #let diff : i64 = i64_sub sum 3i64;
    #let product : i64 = i64_mul diff 2i64;
    #let quotient : i64 = i64_div product b;
    ref_set_ptx i64 array 2i32 quotient;
    ()
}

#fn f32_kernel : (array : ArrayVLPTX f32) -> () #with PTX {
    #let a : f32 = ref_get_ptx f32 array 0i32;
    #let b : f32 = ref_get_ptx f32 array 1i32;
    #let sum : f32 = f32_add a b;
    #let diff : f32 = f32_sub sum 1.5f32;
    #let product : f32 = f32_mul diff 2.0f32;
    #let quotient : f32 = f32_div product b;
    #let root : f32 = f32_sqrt quotient;
    ref_set_ptx f32 array 2i32 root;
    ()
}

#compile_ptx i64_kernel #to i64_kernel_ptx;
#compile_ptx f32_kernel #to f32_kernel_ptx;

#entrypoint main;

#fn main : () #with IO {
    #let init_result : i32 <- IO::cu_init 0i32;
    #let device : i32 = 0i32;
    #letref #excl device : &^ i32 #borrow device;
    #let device_result : i32 <- IO::cu_device_get device 0i32;
    #let device_value : i32 <- ref_get i32 device;
    #let ctx : i64 = 0i64;
    #letref #excl ctx : &^ i64 #borrow ctx;
    #let ctx_result : i32 <- IO::cu_ctx_create_v2 ctx 0i32 device_value;

    #let i64_module : i64 = 0i64;
    #letref #excl i64_module : &^ i64 #borrow i64_module;
    #let i64_ptx : & ArrayVL u8 = i64_kernel_ptx;
    #let i64_module_result : i32 <- IO::cu_module_load_data i64_module i64_ptx;

    #let f32_module : i64 = 0i64;
    #letref #excl f32_module : &^ i64 #borrow f32_module;
    #let f32_ptx : & ArrayVL u8 = f32_kernel_ptx;
    #let f32_module_result : i32 <- IO::cu_module_load_data f32_module f32_ptx;

    #if bool_and (i32_eq i64_module_result 0i32) (i32_eq f32_module_result 0i32) {
        #let _ : () <- IO::exit 0i32;
    } #else {
        #let _ : () <- IO::exit 1i32;
    };
    ()
}
