[workspace]
members = [
    "neco",
    "neco-core-expr",
    "neco-resolver",
    "felis-syn",
]

[workspace.dependencies]
neco = { path = "./neco" }
neco-resolver = { path = "./neco-resolver" }
neco-core-expr = { path = "./neco-core-expr" }
felis-syn = { path = "./felis-syn" }
