[workspace]
members = [
    "felis-syn",
    "felis-type-check",
    "neco",
    "neco-resolver",
]

[workspace.dependencies]
felis-syn = { path = "./felis-syn" }
felis-type-check = { path = "./felis-type-check" }
neco = { path = "./neco" }
neco-resolver = { path = "./neco-resolver" }
