[package]
name = "neco-felis-type-check"
version = "0.1.0"
edition = "2024"

[dependencies]
neco-cic = { path = "../neco-cic" }
neco-felis-syn = { path = "../neco-felis-syn" }

[dev-dependencies]
insta = { workspace = true }
