#use std_core::io::IO;
#use std_core::io::FileDescriptor;
#use std_core::path::PathBuf;

#entrypoint main;

#fn main : () #with IO {
    #let path : PathBuf <- IO::pathbuf_new 32i32;
    #letref #excl path_ref : &^ PathBuf #borrow path;
    #let _ : () <- IO::pathbuf_push path_ref "created.txt";
    #let fd : FileDescriptor <- IO::open path_ref 577i32 420i32;
    #let message_ref : & ArrayVL u8 = "open/write/close fixture\n";
    #let _ : () <- IO::write fd message_ref 25i32;
    #let _ : () <- IO::close fd;
    ()
}
