#use std_core::io::IO;
#use std_core::primitive::bool::bool;
#use std_core::primitive::bool::false;
#use std_core::primitive::bool::true;
#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_set;

#entrypoint main;

#fn main : () #with IO {
    #let value : bool = false;
    #letref #excl value_ref : &^ bool #borrow value;
    ref_set bool value_ref true;
    #let current : bool <- ref_get bool value_ref;
    #if current {
        #let _ : () <- IO::sys_exit 42i32;
    };
    #let _ : () <- IO::sys_exit 1i32;
    ()
}
