#use std_core::io::IO;
#use std_core::io::FileDescriptor;
#use std_core::primitive::u8::u8;

#entrypoint main;

#fn main : () #with IO {
    #let stdin : FileDescriptor <- IO::stdin;
    #let stdout : FileDescriptor <- IO::stdout;
    #let _ @^ bytes_ref : &^ Array u8 1000i32 <- IO::array_new u8 1000i32;
    #let len : i32 <- IO::read stdin bytes_ref 1000i32;
    #let _ : () <- IO::write stdout bytes_ref len;
    ()
}
