#use std_core::io::IO;
#use std_core::ptx::PTX;
#use std_core::ptx::ctaid_x;
#use std_core::ptx::ctaid_y;
#use std_core::ptx::ctaid_z;
#use std_core::ptx::ntid_x;
#use std_core::ptx::ntid_y;
#use std_core::ptx::ntid_z;
#use std_core::ptx::tid_x;
#use std_core::ptx::tid_y;
#use std_core::ptx::tid_z;
#use std_core::primitive::array::ArrayVL;
#use std_core::primitive::array::ArrayVLPTX;
#use std_core::primitive::array::array_get;
#use std_core::primitive::array::array_set;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_eq;
#use std_core::primitive::i64::i64;
#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_set_ptx;
#use std_core::primitive::u8::u8;

#fn special_registers_kernel : (array : ArrayVLPTX i32) -> () #with PTX {
    #let block_sum_xy : i32 = i32_add ctaid_x ctaid_y;
    #let block_sum : i32 = i32_add block_sum_xy ctaid_z;
    #let size_sum_xy : i32 = i32_add ntid_x ntid_y;
    #let size_sum : i32 = i32_add size_sum_xy ntid_z;
    #let thread_sum_xy : i32 = i32_add tid_x tid_y;
    #let thread_sum : i32 = i32_add thread_sum_xy tid_z;
    #let block_and_size_sum : i32 = i32_add block_sum size_sum;
    #let sum : i32 = i32_add block_and_size_sum thread_sum;
    ref_set_ptx i32 array 0i32 sum;
    ()
}

#compile_ptx special_registers_kernel #to special_registers_kernel_ptx;

#entrypoint main;

#fn main : () #with IO {
    #let init_result : i32 <- IO::cu_init 0i32;
    #let device : i32 = 0i32;
    #letref #excl device : &^ i32 #borrow device;
    #let device_result : i32 <- IO::cu_device_get device 0i32;
    #let device_value : i32 = ref_get i32 device;
    #let ctx : i64 = 0i64;
    #letref #excl ctx : &^ i64 #borrow ctx;
    #let ctx_result : i32 <- IO::cu_ctx_create_v2 ctx 0i32 device_value;
    #let module : i64 = 0i64;
    #letref #excl module : &^ i64 #borrow module;
    #let ptx : & ArrayVL u8 = special_registers_kernel_ptx;
    #let module_result : i32 <- IO::cu_module_load_data module ptx;
    #if i32_eq module_result 0i32 {
        ();
    } #else {
        #let _ : () <- IO::exit 2i32;
    };
    #let module_value : i64 = ref_get i64 module;
    #let function : i64 = 0i64;
    #letref #excl function : &^ i64 #borrow function;
    #let function_result : i32 <- IO::cu_module_get_function function module_value ptx;
    #if i32_eq function_result 0i32 {
        ();
    } #else {
        #let _ : () <- IO::exit 3i32;
    };
    #let function_value : i64 = ref_get i64 function;
    #let host_array : ArrayVL i32 <- IO::arrayvl_new i32 1i32;
    array_set host_array 0i32 0i32;
    #let device_array : ArrayVLPTX i32 <- IO::arrayvlptx_new i32 1i32;
    #let copy_to_result : i32 <- IO::arrayvl_to_ptx i32 host_array device_array 1i32;
    #let launch_result : i32 <- IO::cu_launch_kernel function_value device_array 1i32 1i32 1i32 1i32 1i32 1i32 0i32 0i64;
    #let copy_from_result : i32 <- IO::arrayvl_from_ptx i32 device_array host_array 1i32;
    #let result : i32 = array_get host_array 0i32;
    #if i32_eq result 3i32 {
        #let _ : () <- IO::exit 0i32;
    } #else {
        #let _ : () <- IO::exit result;
    };
    ()
}
