#use std_core::io::IO;
#use std_core::primitive::i32::i32_from_u8;
#use std_core::primitive::u8::u8;

#struct Envelope : Type[0] {
    body : Slice u8,
}

#type Event : Type[0] {
    received : Envelope -> Event,
}

#fn event_bytes : (event : Event) -> Slice u8 {
    #match event {
        Event::received envelope => envelope.body,
    }
}

#entrypoint main;

#fn main : () #with IO {
    #let bytes_ref : Slice u8 = event_bytes (Event::received (Envelope { body = "A" }));
    #let code : i32 = i32_from_u8 (bytes_ref .> get 0i32);
    #let _ : () <- IO::exit code;
    ()
}
