#use std_core::io::IO;
#use std_core::primitive::array::Array;
#use std_core::primitive::array::array_get;
#use std_core::primitive::array::array_set;
#use std_core::primitive::i64::i64;
#use std_core::primitive::i64::i64_add;

#entrypoint main;

#fn main : () #with IO {
    #let array_ref : Array i64 3i32 <- IO::array_new i64 3i32;
    #letref #excl array_write_ref : &^ Array i64 3i32 #borrow array_ref;
    array_set array_write_ref 0i64 10i64;
    array_set array_write_ref 1i64 20i64;
    array_set array_write_ref 2i64 12i64;
    #let first : i64 = array_get array_ref 0i64;
    #let second : i64 = array_get array_ref 1i64;
    #let third : i64 = array_get array_ref 2i64;
    #let first_sum : i64 = i64_add first second;
    #let code : i64 = i64_add first_sum third;
    #let _ : () <- IO::exit code;
    ()
}
