#use std_core::io::IO;
#use std_core::primitive::i32::i32_from_u8;
#use std_core::primitive::u8::u8;

#type Message : Type[0] {
    text : Slice u8 -> Message,
}

#fn message_bytes : (message : Message) -> Slice u8 {
    #match message {
        Message::text text => text,
    }
}

#entrypoint main;

#fn main : () #with IO {
    #let bytes_ref : Slice u8 = message_bytes (Message::text "A");
    #let code : i32 = i32_from_u8 (bytes_ref .> get 0i32);
    #let _ : () <- IO::exit code;
    ()
}
