#use std_core::io::IO;
#use std_core::primitive::array::ArrayVL;
#use std_core::primitive::array::array_get;
#use std_core::primitive::i32::i32_from_u8;
#use std_core::primitive::u8::u8;

#type Message : Type[0] {
    text : (& ArrayVL u8) -> Message,
}

#fn message_bytes : (message : Message) -> (& ArrayVL u8) {
    #match message {
        Message::text text => text,
    }
}

#entrypoint main;

    #fn main : () #with IO {
    #let bytes_ref : & ArrayVL u8 = message_bytes (Message::text "A");
    #let byte : u8 = array_get bytes_ref 0i32;
    #let code : i32 = i32_from_u8 byte;
    #let _ : () <- IO::sys_exit code;
    ()
}
