#use std_core::io::IO;
#use std_core::primitive::array::DynArray;
#use std_core::primitive::array::dyn_array_get_i32;
#use std_core::primitive::array::dyn_array_set_i32;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;

#entrypoint main;

#fn sum3 : (array_ref : &^ DynArray i32) -> i32 {
    #let a0 = dyn_array_get_i32 array_ref 0i32;
    #let a1 = dyn_array_get_i32 array_ref 1i32;
    #let a2 = dyn_array_get_i32 array_ref 2i32;
    #let a0_plus_a1 = i32_add a0 a1;
    i32_add a0_plus_a1 a2
}

#fn main : () #with IO {
    #let _ @^ array_ref <- dyn_array_new i32 4i32;
    dyn_array_set_i32 array_ref 0i32 7i32;
    dyn_array_set_i32 array_ref 1i32 14i32;
    dyn_array_set_i32 array_ref 2i32 21i32;
    #let r = sum3 array_ref;
    #let _ <- IO::exit r;
    ()
}
