#use std_core::io::IO;
#use std_core::io::FileDescriptor;
#use std_core::primitive::array::Array;
#use std_core::primitive::array::array_set;
#use std_core::primitive::u8::u8;

#entrypoint main;

#fn main : () #with IO {
    #let stdout : FileDescriptor <- IO::stdout;
    #let bytes_ref : Array u8 0x2i32 <- IO::array_new u8 0x2i32;
    #letref #excl bytes_write_ref : &^ Array u8 0x2i32 #borrow bytes_ref;
    array_set bytes_write_ref 0x0i32 0x41u8;
    array_set bytes_write_ref 0x1i32 0xau8;
    #let _ : () <- IO::sys_write stdout bytes_ref 0x2i32;
    ()
}
