#use std_core::io::IO;
#use std_core::io::FileDescriptor;
#use std_core::path::PathBuf;
#use std_core::primitive::array::Array;
#use std_core::primitive::array::array_set;
#use std_core::primitive::u8::u8;

#entrypoint main;

#fn main : () #with IO {
    #let stdout : FileDescriptor <- IO::stdout;
    #let path_ref : Array u8 12i32 <- IO::array_new u8 12i32;
    array_set path_ref 0i32 0x6du8;
    array_set path_ref 1i32 0x65u8;
    array_set path_ref 2i32 0x73u8;
    array_set path_ref 3i32 0x73u8;
    array_set path_ref 4i32 0x61u8;
    array_set path_ref 5i32 0x67u8;
    array_set path_ref 6i32 0x65u8;
    array_set path_ref 7i32 0x2eu8;
    array_set path_ref 8i32 0x74u8;
    array_set path_ref 9i32 0x78u8;
    array_set path_ref 10i32 0x74u8;
    array_set path_ref 11i32 0x00u8;
    #let path : PathBuf <- IO::pathbuf_new 32i32;
    #letref #excl buf_ref : &^ PathBuf #borrow path;
    #let _ : () <- IO::pathbuf_push buf_ref path_ref;
    #let fd : FileDescriptor <- IO::open buf_ref 0i32 0i32;
    #let bytes_ref : Array u8 128i32 <- IO::array_new u8 128i32;
    #let len : i32 <- IO::read fd bytes_ref 128i32;
    #let _ : () <- IO::close fd;
    #let _ : () <- IO::write stdout bytes_ref len;
    ()
}
