#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_set;
#use std_core::io::IO;
#use std_core::primitive::array::Array;
#use std_core::primitive::array::array_get;
#use std_core::primitive::array::array_set;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;

#entrypoint main;

#fn fill_refs : (value_ref : &^ i32) -> (array_ref : &^ Array i32 2i32) -> () #with IO {
    ref_set i32 value_ref 40i32;
    array_set array_ref 0i32 1i32;
    array_set array_ref 1i32 2i32;
    ()
}

#fn sum_refs : (value_ref : & i32) -> (array_ref : &^ Array i32 2i32) -> i32 #with IO {
    #let value : i32 = ref_get i32 value_ref;
    #let first : i32 = array_get array_ref 0i32;
    #let second : i32 = array_get array_ref 1i32;
    #let array_sum : i32 = i32_add first second;
    i32_add value array_sum
}

#fn main : () #with IO {
    #let value_ref : i32 = 39i32;
    #letref #excl value_ref : &^ i32 #borrow value_ref;
    #let array_ref : Array i32 2i32 <- IO::array_new i32 2i32;
    fill_refs value_ref array_ref;
    #let code : i32 <- sum_refs value_ref array_ref;
    #let _ : () <- IO::exit code;
    ()
}
