#use std_core::io::IO;
#use std_core::io::FileDescriptor;
#use std_core::path::PathBuf;
#entrypoint main;

#fn main : () #with IO {
    #let stdout : FileDescriptor <- IO::stdout;
    #let path : PathBuf <- IO::pathbuf_new 32i32;
    #letref #excl path_ref : &^ PathBuf #borrow path;
    #let _ : () <- IO::pathbuf_push path_ref "message.txt";
    #let fd : FileDescriptor <- IO::sys_open path_ref 0i32 0i32;
    #let bytes_arrayvl : ArrayVL u8 <- IO::arrayvl_new u8 128i32;
    #letref #excl bytes_arrayvl_ref : &^ ArrayVL u8 #borrow bytes_arrayvl;
    #let len : i32 <- IO::sys_read fd bytes_arrayvl_ref 128i32;
    #let _ : () <- IO::sys_close fd;
    #let _ : () <- IO::sys_write stdout bytes_arrayvl_ref len;
    ()
}
