#use std_core::io::IO;
#entrypoint main;

#fn main : () #with IO {
    #let stdout <- IO::stdout;
    #let _ @ path_ref = "message.txt";
    #let path_bytes_ref = path_ref .> as_bytes;
    #let fd <- IO::open path_bytes_ref 0i32 0i32;
    #let _ @^ bytes_ref <- IO::raw_array_new u8 128i32;
    #let len <- IO::read fd bytes_ref 128i32;
    #let _ <- IO::close fd;
    #let _ <- IO::write stdout bytes_ref len;
    ()
}
