#use std_core::primitive::reference::ref_get;
#use std_core::io::IO;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;

#entrypoint main;

#fn add1 : (value_ref : & i32) -> i32 {
    i32_add ((ref_get i32 value_ref)) 1i32
}

#fn main : () #with IO {
    #let value_ref : i32 = 41i32;
    #letref value_ref : & i32 #borrow value_ref;
    #let r : i32 = add1 value_ref;
    #let _ : () <- IO::exit r;
    ()
}
