#use std_core::io::IO;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_from_u8;
#use std_core::primitive::u8::u8;

#entrypoint main;

#fn main : () #with IO {
    #let stdout <- IO::stdout;
    #let path_ref <- IO::arg 1i32;
    #let digits_ref <- IO::arg 2i32;
    #let fd <- IO::open path_ref 0i32 0i32;
    #let _ @^ bytes_ref <- IO::array_new u8 64i32;
    #let len <- IO::read fd bytes_ref 64i32;
    #let _ <- IO::close fd;
    #let _ <- IO::write stdout bytes_ref len;
    #let left = i32_from_u8 (digits_ref .> get 0i32);
    #let right = i32_from_u8 (digits_ref .> get 1i32);
    #let code = i32_add left right;
    #let _ <- IO::exit code;
    ()
}
