#use std_core::io::IO;
#use std_core::io::FileDescriptor;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_from_u8;
#use std_core::primitive::u8::u8;

#entrypoint main;

#fn main : () #with IO {
    #let stdout : FileDescriptor <- IO::stdout;
    #let path_ref : & Array u8 <- IO::arg 1i32;
    #let digits_ref : & Array u8 <- IO::arg 2i32;
    #let fd : FileDescriptor <- IO::open path_ref 0i32 0i32;
    #letref #excl bytes_ref : &^ Array u8 64i32 <- IO::array_new u8 64i32;
    #let len : i32 <- IO::read fd bytes_ref 64i32;
    #let _ : () <- IO::close fd;
    #let _ : () <- IO::write stdout bytes_ref len;
    #let left : i32 = i32_from_u8 (digits_ref .> get 0i32);
    #let right : i32 = i32_from_u8 (digits_ref .> get 1i32);
    #let code : i32 = i32_add left right;
    #let _ : () <- IO::exit code;
    ()
}
