#use std_core::io::IO;
#use std_core::ptx::PTX;
#use std_core::primitive::array::ArrayVL;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i64::i64;
#use std_core::primitive::reference::ref_get;
#use std_core::primitive::u8::u8;

#fn empty_kernel : () #with PTX {
    ()
}

#compile_ptx empty_kernel #to empty_kernel_ptx;

#entrypoint main;

#fn main : () #with IO {
    #let init_result : i32 <- IO::cu_init 0i32;
    #let device : i32 = 0i32;
    #letref #excl device : &^ i32 #borrow device;
    #let device_result : i32 <- IO::cu_device_get device 0i32;
    #let device_value : i32 = ref_get i32 device;
    #let ctx : i64 = 0i64;
    #letref #excl ctx : &^ i64 #borrow ctx;
    #let ctx_result : i32 <- IO::cu_ctx_create_v2 ctx 0i32 device_value;
    #let module : i64 = 0i64;
    #letref #excl module : &^ i64 #borrow module;
    #let ptx : & ArrayVL u8 = empty_kernel_ptx;
    #let module_result : i32 <- IO::cu_module_load_data module ptx;
    #let _ : () <- IO::exit module_result;
    ()
}
