#use std_core::primitive::array::ArrayVLPTX;
#use std_core::primitive::f32::f32;
#use std_core::primitive::f32::f32_gte;
#use std_core::primitive::reference::ref_get_ptx;
#use std_core::primitive::reference::ref_set_ptx;

#fn threshold_kernel : (array : ArrayVLPTX f32) -> () #with PTX {
    #let value : f32 = ref_get_ptx f32 array 0i32;
    #if f32_gte value 1.0f32 {
        ref_set_ptx f32 array 1i32 2.0f32;
    } #else {
        ref_set_ptx f32 array 1i32 3.0f32;
    };
    ()
}

#compile_ptx threshold_kernel #to threshold_kernel_ptx;

#entrypoint main;

#fn main : () #with IO {
    ()
}
