#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_set;
#use std_core::io::IO;
#use std_core::primitive::i32::i32;

#type(rc) Token : Type[0] {
    empty : Token,
    number : i32 -> Token,
}

#fn apply_token_ref : (token_ref : &^ Token) -> (code_ref : &^ i32) -> () #with IO {
    #match token_ref {
        Token::empty => ref_set i32 code_ref 1i32,
        Token::number value_ref => {
            ref_set i32 value_ref 42i32;
            #let value : i32 = ref_get i32 value_ref;
            ref_set i32 code_ref value;
        }
    };
    ()
}

#entrypoint main;

#fn main : () #with IO {
    #let token : Token = Token::number 1i32;
    #letref #excl token_ref : &^ Token #borrow token;
    #let code_ref : i32 = 0i32;
    #letref #excl code_ref : &^ i32 #borrow code_ref;
    apply_token_ref token_ref code_ref;
    #let code : i32 = ref_get i32 code_ref;
    #let _ : () <- IO::exit code;
    ()
}
