#use std_core::io::IO;
#use std_core::primitive::array::append_nul_terminated_u8;
#use std_core::primitive::array::append_u8;
#use std_core::primitive::array::fill_u8;
#use std_core::primitive::i32::i32_from_u8;

#entrypoint main;

#fn main : () #with IO {
    #letref source_ref : & Array u8 := "ab";
    #let source_bytes_ref : & Array u8 = source_ref .> as_bytes;
    #letref #excl buffer_ref : &^ RawArray u8 <- IO::raw_array_new u8 8i32;
    #letref #excl index_ref : &^ i32 := 0i32;
    fill_u8 buffer_ref '.';
    append_nul_terminated_u8 source_bytes_ref buffer_ref index_ref;
    append_u8 buffer_ref index_ref 'c';
    #let exit_code : u8 = buffer_ref .> get 2i32;
    #let _ : () <- IO::exit (i32_from_u8 exit_code);
    ()
}
