#use std_core::io::IO;
#use std_core::primitive::array::ArrayVL;
#use std_core::primitive::array::append_dyn_nul_terminated_u8;
#use std_core::primitive::array::append_u8;
#use std_core::primitive::array::array_get;
#use std_core::primitive::array::fill_u8;
#use std_core::primitive::i32::i32_from_u8;

#entrypoint main;

#fn main : () #with IO {
    #let source_bytes_ref : & ArrayVL u8 = "ab";
    #let buffer_arrayvl : ArrayVL u8 <- IO::arrayvl_new u8 8i32;
    #letref #excl buffer_arrayvl_ref : &^ ArrayVL u8 #borrow buffer_arrayvl;
    #let index_ref : i32 = 0i32;
    #letref #excl index_ref : &^ i32 #borrow index_ref;
    fill_u8 buffer_arrayvl_ref '.';
    append_dyn_nul_terminated_u8 source_bytes_ref buffer_arrayvl_ref index_ref;
    append_u8 buffer_arrayvl_ref index_ref 'c';
    #let exit_code : u8 = array_get buffer_arrayvl_ref 2i32;
    #let code : i32 = i32_from_u8 exit_code;
    #let _ : () <- IO::sys_exit code;
    ()
}
