#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_set;
#use std_core::io::IO;
#use std_core::primitive::array::ArrayVL;
#use std_core::primitive::array::array_get;
#use std_core::primitive::array::array_len;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_gte;
#use std_core::primitive::u8::u8_eq;

#fn find_byte_offset : (bytes_ref : & ArrayVL u8) -> (target : u8) -> (len : i32) -> (offset_ref : &^ i32) -> () #with IO {
    ref_set i32 offset_ref 0i32;
    #loop {
        #let offset : i32 = ref_get i32 offset_ref;
        #if i32_gte offset len {
            #break;
        };
        #let byte : u8 = array_get bytes_ref offset;
        #if u8_eq byte target {
            #break;
        };
        #let next_offset : i32 = i32_add offset 1i32;
        ref_set i32 offset_ref next_offset;
    };
    ()
}

#entrypoint main;

#fn main : () #with IO {
    #let bytes_ref : & ArrayVL u8 = "abc:42";
    #let offset_ref : i32 = 0i32;
    #letref #excl offset_ref : &^ i32 #borrow offset_ref;
    #let len : i32 = array_len bytes_ref;
    find_byte_offset bytes_ref ':' len offset_ref;
    #let offset : i32 = ref_get i32 offset_ref;
    #let code : i32 = i32_add offset 39i32;
    #let _ : () <- IO::exit code;
    ()
}
