#use std_core::io::IO;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_set;

#entrypoint main;

#proc write_ref : (value_ref : &^ i32) -> () {
    ref_set i32 value_ref 41i32;
    ()
}

#fn read_ref : (value_ref : & i32) -> i32 {
    ref_get i32 value_ref
}

#fn main : () #with IO {
    #let value_ref : i32 = 0i32;
    #letref #excl value_ref : &^ i32 #borrow value_ref;
    write_ref value_ref;
    #let first : i32 = ref_get i32 value_ref;
    #let second : i32 = read_ref value_ref;
    #let code : i32 = i32_add first second;
    #let _ : () <- IO::exit code;
    ()
}
