#use std_core::io::IO;
#use std_core::primitive::u8::u8;
#use std_core::primitive::u8::u8_add;
#use std_core::primitive::u8::u8_sub;
#use std_core::primitive::u8::u8_mul;
#use std_core::primitive::u8::u8_div;
#use std_core::primitive::u8::u8_mod;

#entrypoint main;

#fn main : () #with IO {
    #let a : u8 = 3u8;
    #let b : u8 = 7u8;
    #let c : u8 = 4u8;
    #let d : u8 = 21u8;
    #let e : u8 = 3u8;
    #let f : u8 = 80u8;
    #let x1 : u8 = u8_add a b;
    #let x2 : u8 = u8_sub x1 c;
    #let x3 : u8 = u8_mul x2 d;
    #let x4 : u8 = u8_div x3 e;
    #let x5 : u8 = u8_mod x4 f;
    #let _ : () <- IO::exit x5;
    ()
}
