#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_set;
#use std_core::io::IO;
#use std_core::primitive::array::Array;
#use std_core::primitive::array::array_get;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_from_u8;

#entrypoint main;

#proc read_digits : (digits_ref : &^ Array u8) -> (left_ref : &^ i32) -> (right_ref : &^ i32) -> () {
    ref_set i32 left_ref (i32_from_u8 (array_get digits_ref 0i32));
    ref_set i32 right_ref (i32_from_u8 (array_get digits_ref 1i32));
    ()
}

#fn main : () #with IO {
    #let digits_ref : & Array u8 <- IO::arg 1i32;
    #let left_ref : i32 = 0i32;
    #letref #excl left_ref : &^ i32 #borrow left_ref;
    #let right_ref : i32 = 0i32;
    #letref #excl right_ref : &^ i32 #borrow right_ref;
    read_digits digits_ref left_ref right_ref;
    #let code : i32 = i32_add ((ref_get i32 left_ref)) ((ref_get i32 right_ref));
    #let _ : () <- IO::exit code;
    ()
}
