#use std_core::io::IO;
#use std_core::primitive::array::Array;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_from_u8;

#entrypoint main;

#proc read_digits : (digits_ref : &^ Array u8) -> (left_ref : & i32) -> (right_ref : & i32) -> () {
    left_ref .> set (i32_from_u8 (digits_ref .> get 0i32));
    right_ref .> set (i32_from_u8 (digits_ref .> get 1i32));
    ()
}

#fn main : () #with IO {
    #let digits_ref <- IO::arg 1i32;
    #let _ @ left_ref = 0i32;
    #let _ @ right_ref = 0i32;
    read_digits digits_ref left_ref right_ref;
    #let code = i32_add (left_ref .> get) (right_ref .> get);
    #let _ <- IO::exit code;
    ()
}
