#use std_core::io::IO;
#use std_core::primitive::vec::Vec;
#use std_core::primitive::array::ArrayVL;
#use std_core::primitive::vec::vec_get;
#use std_core::primitive::vec::vec_set;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_from_u8;

#entrypoint main;

#fn write_first : (t : Type[0]) -> (array : Vec t) -> (value : t) -> () #with IO {
    vec_set t array 0i32 value;
    ()
}

#fn main : () #with IO {
    #let bytes_arrayvl : ArrayVL u8 <- IO::arrayvl_new u8 4i32;
    #letref #excl bytes_arrayvl_ref : &^ ArrayVL u8 #borrow bytes_arrayvl;
    #let bytes : Vec u8 = Vec::vec u8 bytes_arrayvl 1i64;
    write_first u8 bytes 1u8;
    #let byte : u8 <- vec_get u8 bytes 0i32;

    #let numbers_arrayvl : ArrayVL i32 <- IO::arrayvl_new i32 4i32;
    #letref #excl numbers_arrayvl_ref : &^ ArrayVL i32 #borrow numbers_arrayvl;
    #let numbers : Vec i32 = Vec::vec i32 numbers_arrayvl 1i64;
    write_first i32 numbers 41i32;
    #let number : i32 <- vec_get i32 numbers 0i32;

    #let value : i32 = i32_add (i32_from_u8 byte) number;
    #let _ : () <- IO::sys_exit value;
    ()
}
