#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_set;
#use std_core::io::IO;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_eq;

#entrypoint main;

#fn main : () #with IO {
    #let counter : i32 = 0i32;
    #letref #excl counter : &^ i32 #borrow counter;
    #let sum : i32 = 0i32;
    #letref #excl sum : &^ i32 #borrow sum;
    #loop {
        #let counter_value : i32 = ref_get i32 counter;
        #let new_counter : i32 = i32_add counter_value 1i32;
        ref_set i32 counter new_counter;
        #let counter_after_increment : i32 = ref_get i32 counter;
        #if i32_eq counter_after_increment 5i32 {
            #continue;
        };
        #let sum_value : i32 = ref_get i32 sum;
        #let counter_for_sum : i32 = ref_get i32 counter;
        #let new_sum : i32 = i32_add sum_value counter_for_sum;
        ref_set i32 sum new_sum;
        #let counter_after_sum : i32 = ref_get i32 counter;
        #if i32_eq counter_after_sum 10i32 {
            #break;
        };
    };
    #let code : i32 = ref_get i32 sum;
    #let _ : () <- IO::exit code;
    ()
}
