#use std_core::io::IO; // import IO
#use std_core::io::FileDescriptor;

/* comments can appear between top-level items */
#entrypoint main;

/* comments can also wrap statement boundaries */
#fn main : () #with IO {
    #let stdout : FileDescriptor <- IO::stdout; // stdout fd
    #let hello_ref : Slice u8 =
        /* comments can appear before a literal */
        "Hello, world!\n";
    #let _ : () <- IO::write stdout hello_ref 14i32; /* trailing block comment */
    ()
}
