#use std_core::io::IO;
#use std_core::primitive::array::ArrayVL;
#use std_core::primitive::array::array_set;
#use std_core::primitive::i32::i32;
#use std_core::result::Result;
#use std_core::string::String;
#use std_core::string::string_from_arrayvl_parts;
#use std_json::Json;
#use std_json::JsonParseError;
#use std_json::json_parse;
#use std_json::json_score;

#entrypoint main;

#fn main : () #with IO {
    #let parse_source_arrayvl : ArrayVL u8 <- IO::arrayvl_new u8 5i32;
    #letref #excl parse_source_arrayvl_ref : &^ ArrayVL u8 #borrow parse_source_arrayvl;
    array_set parse_source_arrayvl_ref 0i32 'f';
    array_set parse_source_arrayvl_ref 1i32 'a';
    array_set parse_source_arrayvl_ref 2i32 'l';
    array_set parse_source_arrayvl_ref 3i32 's';
    array_set parse_source_arrayvl_ref 4i32 'e';
    #let parse_source : String = string_from_arrayvl_parts parse_source_arrayvl 5i32 5i32;
    #let parsed_result : Result Json JsonParseError <- json_parse parse_source;
    #let parsed : Json = #match parsed_result {
        Result::ok _ _ value => value,
        Result::err _ _ _ => Json::null,
    };
    #let parsed_code : i32 = json_score parsed;
    #let _ : () <- IO::sys_exit parsed_code;
    ()
}
