#use std_core::io::IO;
#use std_core::primitive::i32::i32;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_sub;
#use std_core::primitive::i32::i32_mul;
#use std_core::primitive::i32::i32_div;
#use std_core::primitive::i32::i32_mod;

#entrypoint main;

#fn f : (a : i32) -> i32 {
    #let b : i32 = 7i32;
    #let c : i32 = 4i32;
    #let d : i32 = 61i32;
    #let e : i32 = 3i32;
    #let f : i32 = 80i32;
    #let x1 : i32 = i32_add a b;
    #let x2 : i32 = i32_sub x1 c;
    #let x3 : i32 = i32_mul x2 d;
    #let x4 : i32 = i32_div x3 e;
    #let x5 : i32 = i32_mod x4 f;
    x5
}

#fn main : () #with IO {
    #let x : i32 = f 3i32;
    #let _ : () <- IO::exit x;
    ()
}
