#use std_core::primitive::reference::ref_get;
#use std_core::primitive::reference::ref_set;
#use std_core::io::IO;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_eq;

#entrypoint main;

#fn main : () #with IO {
    #let counter : i32 = 1i32;
    #letref #excl counter : &^ i32 #borrow counter;
    #let sum : i32 = 0i32;
    #letref #excl sum : &^ i32 #borrow sum;
    #loop {
        #let new_sum : i32 = i32_add ((ref_get i32 sum)) ((ref_get i32 counter));
        ref_set i32 sum new_sum;
        #if i32_eq ((ref_get i32 counter)) 10i32 {
            #break;
        };
        #let new_counter : i32 = i32_add ((ref_get i32 counter)) 1i32;
        ref_set i32 counter new_counter;
    };
    #let _ : () <- IO::exit ((ref_get i32 sum));
    ()
}
