#use std_core::io::IO;
#use std_core::primitive::i32::i32_add;
#use std_core::primitive::i32::i32_eq;

#entrypoint main;

#proc main : () #with IO {
    #let counter : i32 = 1i32;
    #letref #excl counter : &^ i32 #borrow counter;
    #let sum : i32 = 0i32;
    #letref #excl sum : &^ i32 #borrow sum;
    #loop {
        #let new_sum : i32 = i32_add (sum .> get) (counter .> get);
        sum .> set new_sum;
        #if i32_eq (counter .> get) 10i32 {
            #break;
        };
        #let new_counter : i32 = i32_add (counter .> get) 1i32;
        counter .> set new_counter;
    };
    #let _ : () <- IO::exit (sum .> get);
    ()
}
