#entrypoint main;

#use_builtin "syscall" #as __syscall;
#use_builtin "u64_add" #as __u64_add;
#use_builtin "u64" #as __u64;

#struct Vec3 {
    x: __u64,
    y: __u64,
    z: __u64,
}

#proc main : () -> () {
    #let v = Vec3 {
        x: 18,
        y: 14,
        z: 10,
    };

    #let a = __u64_add v.x v.y;
    #let b = __u64_add a v.z;

    #let syscall_id = 231u64;
    #let error_code = b;
    __syscall syscall_id error_code 0 0 0 0;
}
