name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Deploy job
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v3

      # llvm-cov
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Create llvm-cov report
        run: cargo llvm-cov test --html --output-dir ../pages/llvm-cov
        working-directory: neco-rs

      # upload
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
