name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Deploy job
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
          components: llvm-tools-preview

      # Setup mdbook
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      # index.html
      - name: Copy index.html
        run: cp pages-src/index.html pages

      # create llvm-cov report
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Create llvm-cov report
        run: cargo llvm-cov test --html --output-dir ../pages/llvm-cov --offline
        working-directory: neco-rs

      # create the-felis-programming-language
      - name: Build 'The Felis Programming Language'
        run: |
          mdbook build
          cp -r book ../../pages/the-felis-programming-language
        working-directory: pages-src/the-felis-programming-language

      # upload
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
